console.log("Program 1:")
const createPersonObj = (firstName, lastName) => ({firstName: firstName, lastName: lastName})
console.log(createPersonObj("Anish", "Singh"))
console.log("---- ---- ----")
console.log("Program 2:")
const createStringObj = (str) => ({length: str.length, uppercase: str.toUpperCase()})
console.log(createStringObj("hello"))
console.log("---- ---- ----")
console.log("Program 3:")
const createPersonDetailObj = (firstName, lastName, age, phoneNumber) => ({fullName: firstName + lastName, age: age, phoneNumber: phoneNumber})
console.log(createPersonDetailObj("Anish ", "Singh", 32, 8899556622))
console.log("---- ---- ----")
console.log("Program 4:")
const createWordObj = (firstWord, secondWord) => ({concatenation: firstWord + " " + secondWord, charCount: firstWord.length + secondWord.length})
console.log(createWordObj("Hello", "World"))
console.log("---- ---- ----")
console.log("Program 5:")
const calculateCircleProperties = (radius) => ({circumference: 2 * Math.PI * radius, area: Math.PI * radius * radius})
console.log(calculateCircleProperties(5))
console.log("---- ---- ----")
console.log("Program 6:")
const calculateDifferenceAndQuotient = (num1, num2) => ({difference: num1 - num2, quotient: num1 / num2})
console.log(calculateDifferenceAndQuotient(10, 2))
console.log("---- ---- ----")
console.log("Program 7")
const analyzeSentence = (sent) => ({wordCount: sent.split(' ').length})
console.log(analyzeSentence("JavaScript is fun"))
console.log("---- ---- ----")
console.log("Program 8:")
const calculateSquareAndCube = (num) => ({square: num*num, cube: num*num*num})
console.log(calculateSquareAndCube(4))
console.log("---- ---- ----")
console.log("Program 9:")
const checkNumber = (num) => ({isPositive: num > 0, isNegative: num < 0})
console.log(checkNumber(-7))
console.log(checkNumber(5))